Remove libgettextlib.a
When building under Koji:

error: File not found: /builddir/build/BUILDROOT/mingw-gettext-0.22-2.fc39.noarch/usr/i686-w64-mingw32/sys-root/mingw/lib/libgettextlib.a

Somehow Koji runs extra rules that delete the *.a files, unclear why.

Fixes: commit 74b5a7644ba8e184a391cec05e7e159b1e3d2410