Fix SONAME of libgettext* DLLs
These were not found during the mass rebuild:

    File not found: /home/rjones/rpmbuild/BUILDROOT/mingw-gettext-0.22-2.fc39.x86_64/usr/i686-w64-mingw32/sys-root/mingw/bin/libgettextlib-0-21-1.dll
    File not found: /home/rjones/rpmbuild/BUILDROOT/mingw-gettext-0.22-2.fc39.x86_64/usr/i686-w64-mingw32/sys-root/mingw/bin/libgettextsrc-0-21-1.dll

Local examination shows that the version number has changed to 0-22.

After fixing that, we get this error:

error: Installed (but unpackaged) file(s) found:
   /usr/i686-w64-mingw32/sys-root/mingw/lib/libgettextlib.a
   /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libgettextlib.a